<?php

declare(strict_types=1);

namespace App\Http\Middleware;

use AltUU\Domains\Diagnostics\Enums\DiagnosticEventTypeEnum;
use AltUU\Domains\Diagnostics\Enums\DiagnosticLevelEnum;
use App\Services\Diagnostics\DiagnosticContext;
use App\Services\Diagnostics\DiagnosticRecorder;
use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Gives every request a correlation id and records how it went.
 *
 * The id is generated by the frontend and sent as X-Request-Id, so a failure
 * the server never saw — an offline device, a DNS failure — still has an id
 * the client can log against. We echo it back so the two halves of the same
 * call can be lined up in the exported bundle.
 */
final class RecordDiagnostics
{
    public const REQUEST_ID_HEADER = 'X-Request-Id';

    public const OPERATION_HEADER = 'X-Alt-UU-Op';

    public function __construct(private readonly DiagnosticRecorder $recorder) {}

    public function handle(Request $request, Closure $next): Response
    {
        $requestId = $this->resolveRequestId($request);
        $operation = $this->resolveOperation($request);

        DiagnosticContext::putRequestId($requestId);

        if ($operation !== null) {
            DiagnosticContext::putOperation($operation);
        }

        $startedAt = microtime(true);

        /** @var Response $response */
        $response = $next($request);

        $response->headers->set(self::REQUEST_ID_HEADER, $requestId);

        $this->record($request, $response, $requestId, $operation, $startedAt);

        return $response;
    }

    private function record(
        Request $request,
        Response $response,
        string $requestId,
        ?string $operation,
        float $startedAt,
    ): void {
        if (! $this->shouldRecord($request)) {
            return;
        }

        $status = $response->getStatusCode();

        $this->recorder->record(
            DiagnosticEventTypeEnum::ApiRequest,
            mb_strtoupper($request->method()).' /'.ltrim($request->path(), '/'),
            $this->levelFor($status),
            op: $operation,
            requestId: $requestId,
            status: $status,
            durationMs: (int) round((microtime(true) - $startedAt) * 1000),
        );
    }

    /**
     * Only our own JSON endpoints are worth recording. The SPA shell and
     * static assets would just crowd out real events in the bounded log.
     *
     * The diagnostics endpoints themselves are excluded: reading, exporting
     * or clearing the log should not write to it. Otherwise pressing 清除
     * would leave the DELETE that cleared it sitting in an otherwise empty
     * list.
     */
    private function shouldRecord(Request $request): bool
    {
        if ($request->is('api/diagnostics/*')) {
            return false;
        }

        return $request->is('api/*')
            || $request->is('login', 'logout', 'study-time')
            || $request->expectsJson();
    }

    private function levelFor(int $status): DiagnosticLevelEnum
    {
        return match (true) {
            $status >= 500 => DiagnosticLevelEnum::Error,
            $status >= 400 => DiagnosticLevelEnum::Warning,
            default => DiagnosticLevelEnum::Info,
        };
    }

    private function resolveRequestId(Request $request): string
    {
        $supplied = (string) $request->header(self::REQUEST_ID_HEADER, '');

        // Only accept a well-formed id, so a crafted header cannot inject
        // arbitrary text into the log.
        if (preg_match('/^[A-Za-z0-9-]{4,64}$/', $supplied) === 1) {
            return $supplied;
        }

        // Must be random, not time-ordered: the first bytes of an ordered
        // UUID are a timestamp, so truncating one collides for requests that
        // arrive in the same instant — exactly the concurrent case a
        // correlation id exists to untangle.
        return bin2hex(random_bytes(4));
    }

    private function resolveOperation(Request $request): ?string
    {
        $supplied = (string) $request->header(self::OPERATION_HEADER, '');

        return preg_match('/^[a-z0-9._-]{1,64}$/i', $supplied) === 1 ? $supplied : null;
    }
}
