<native:media-player
    ref="player"
    src="{{ $src }}"
    :kind="$kind"
    :title="$title"
    :course-name="$courseName"
    :poster="$poster"
    :subtitles="$subtitles"
    :start="$start"
    :rate="$rate"
    :appearance="$appearanceValue"
    :watermark="$watermark"
    :autoplay="$autoplay"
    :session-context="$sessionContextJson"
    class="{{ $playerClass }}"
    on-progress="onProgress"
    on-state-change="onStateChange"
    on-ended="onEnded"
    on-error="onError"
/>
